name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  job:
    runs-on: ubuntu-latest

    env:
      #CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      #WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      #WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0  # gets entire git history, needed for automatic changelogs

      - uses: BigWigsMods/packager@v2
